repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [commit,push]

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        args: ["--line-length", "79"]
        stages: [commit,push]

  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        stages: [commit,push]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
    hooks:
      - id: commitizen
        entry: cz
        args: ['check', '--commit-msg-file', '.git/COMMIT_EDITMSG']
        pass_filenames: false
        language: python
        stages: [commit-msg,push]

default_language_version:
    python: python3.10